accounts/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct  9 19:30:23 2024

@author: yuki
"""

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    ]

photo/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  7 21:19:35 2024

@author: yuki
"""

from django.urls import path
from . import views

app_name = 'photo'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/', views.CreatePhotoView.as_view(), name='post'),
    path('post_done/', views.PostSuccessView.as_view(), name='post_done'),
    path('photos/<int:category>', views.CategoryView.as_view(), name='photos_cat'),
    path('user-list/<int:user>', views.UserView.as_view(), name='user_list'),
    path('photo-detail/<int:pk>', views.DetailView.as_view(), name='photo_detail'),
    path('mypage/', views.MypageView.as_view(), name='mypage'),
    path('photo/<int:pk>/delete/', views.PhotoDeleteView.as_view(), name='photo_delete'),
    ]

photoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('photo.urls')),
    path('', include('accounts.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name="password_reset.html"), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name="password_reset_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name="password_reset_form.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name="password_reset_done.html"), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

photo/models.py
from django.db import models

from accounts.models import CustomUser

class Category(models.Model):
    title = models.CharField(
        verbose_name ='カテゴリ',
        max_length=20
        )
    
    def __str__(self):
        return self.title
    
class PhotoPost(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE
        )
    category = models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT
        )
    title = models.CharField(
        verbose_name='タイトル',
        max_length=200
        )
    comment = models.TextField(
        verbose_name='コメント',
        )
    image1 = models.ImageField(
        verbose_name='イメージ｀1',
        upload_to = 'photos',
        )
    image2 = models.ImageField(
        verbose_name='イメージ2',
        upload_to = 'photos',
        blank=True,
        null=True
        )
    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
        )
    def __str__(self):
        return self.title
    
    
    
    
    
    
    

accounts/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  8 19:27:33 2024

@author: yuki
"""
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'email', 'password1','password2' )

photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost

class PhotoPostForm(ModelForm):
    class Meta:
        model = PhotoPost
        fields = ['category', 'title', 'comment', 'image1', 'image2']
        
        
        

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "signup.html"
    success_url = reverse_lazy('accounts:signup_success')
    
    def form_valid(self, form):
        user = form.save()
        self.object = user
        return super().form_valid(form)
    
class SignUpSuccessView(TemplateView):
    template_name = "signup_success.html"

photo/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView, DetailView, DeleteView
from django.urls import reverse_lazy
from .forms import PhotoPostForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import PhotoPost

class IndexView(ListView):
    template_name = 'index.html'
    queryset = PhotoPost.objects.order_by('-posted_at')
    paginate_by = 9
    
@method_decorator(login_required, name='dispatch')
class CreatePhotoView(CreateView):
    form_class = PhotoPostForm
    template_name = "post_photo.html"
    success_url = reverse_lazy('photo:post_done')
    
    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)
    
class PostSuccessView(TemplateView):
    template_name = 'post_success.html'
    

class CategoryView(ListView):
    template_name = 'index.html'
    paginate_by = 9
    def get_queryset(self):
        category_id = self.kwargs['category']
        categories = PhotoPost.objects.filter(
            category=category_id).order_by('-posted_at')
        return categories
    
class UserView(ListView):
    template_name = 'index.html'
    paginate_by = 9
    def get_queryset(self):
        user_id = self.kwargs['user']
        user_list = PhotoPost.objects.filter(
            user=user_id).order_by('-posted_at')
        return user_list
    
class DetailView(DetailView):
    template_name = 'detail.html'
    model = PhotoPost
    
class MypageView(ListView):
    template_name = 'mypage.html'
    paginate_by = 9
    def get_queryset(self):
        queryset = PhotoPost.objects.filter(
            user=self.request.user).order_by('posted_at')
        return queryset

class PhotoDeleteView(DeleteView):
    model = PhotoPost
    template_name = 'photo_delete.html'
    success_url = reverse_lazy('photo:mypage')
    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)
    

accounts/templates/login.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更 -->
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <!-- タイトル変更 -->
    <title>Log in</title>

    <!-- <link rel="canonical"...>を削除 -->    

    <!-- Bootstrap core CSS -->
    <!--
    Bootstrap core CSSを読み込むコードをBootstrapからコピーして
    <link>タグを書き換え -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <!-- 「static/css/signin.css」の読み込み -->
    <link href={% static "css/signin.css" %}
          rel="stylesheet">
  </head>
  <body class="text-center">    
    <main class="form-signin">
      <!-- ユーザー名とパスワードが一致しない場合のメッセージ -->
      {% if form.errors %}
        <p style="color: red">ユーザー名とパスワードが一致しません。</p>
      {% endif %}
      <!-- ログインのフォームを配置 -->
      <form method="post">
        {% csrf_token %}
        <!-- Bootstrapのロゴを表示 -->
        <!-- 「static/img/bootstrap-logo.svg」の読み込み -->
        <img class="mb-4"
             src={% static "img/bootstrap-logo.svg" %}
             alt="" width="72"
             height="57">
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
        <!--
        <div class="form-floating">～</div>の2つのブロックを削除して
        以下に書き換え
        -->
        <!-- Usernameのラベル(非表示) -->
        <label for="Username" class="visually-hidden">
          User name</label>
        <!-- usernameの<input>タグを出力-->
        <!-- name属性の値はLoginViewで定義されているフィールド名username -->
        <input type="text"
               name="username"
               id="id_username"
               maxlength="150"
               autocapitalize="none"
               autocomplete="username"
               class="form-control"
               placeholder="ユーザー名"
               required autofocus>
        <!-- Passwordのラベル(非表示) -->
        <label for="Password" class="visually-hidden">
          Password</label>
        <!-- passwordの<input>タグを出力-->
        <!-- name属性の値はLoginViewで定義されているフィールド名password -->
        <input type="password"
               name="password"
               id="id_password"
               autocomplete="current-password"
               class="form-control"
               placeholder="パスワード"
               required autofocus>
        
        <!-- <button>～</button>を書き換えてログインボタンを配置 -->
            <input class="w-100 btn btn-lg btn-primary"
                   type="submit"
                   value="ログイン">
        
        <!-- パスワードリセットページのリンクテキスト -->
        <br><br>
        <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか?</a><p>
        <!-- ログイン直後のリダイレクト先(トップページ)のURLパターンを設定 -->
        <input type="hidden"
               name="next"
               value="{% url 'photo:index' %}">
      </form>
    </main>   
  </body>
</html>

accounts/templates/logout.html
{% extends 'base.html' %}{% block title %}Log out{% endblock %}    {% block contents %}    <div class="container">        <div class="row">            <div class="col offset-4 py-4">            <h3>ログアウトしました</h3>                        <p><a href="{% url 'photo:index' %}">トップページ</a><p>    {% endblock %}

accounts/templates/password_reset.html
{% extends 'base.html' %}{% block title %}Reset Password{% endblock %}    {% block contents %}    <div class="container">        <div class="row">            <div class="col py-4">                <hr>                <h3>パスワードをリセットしますか？</h3>                <p>                登録済みのメールアドレスを入力してください。                パスワードリセットのリンクを記載したメールをすぐにお届けします。                </p>                <br>                <form action="", method="POST" class="text-center">                    {% csrf_token %}                    {{form}}                    <input type="submit" value="メールを受け取る" /><br>                </form>                <br>                                <a href="{% url 'photo:index' %}">Photo Gallery</a>                <hr>            </div>                </div>    </div>    {% endblock %}

accounts/templates/password_reset_done.html
<! doctype html><html lang="ja">    <head>        <style>            .pad{            background-color: lavender;            border: solid 2px;            padding-top: 30px;            padding-bottom: 50px;            padding-left: 100px;            margin-top: 50px;            maegin-right: 70px;            margin-left: 70px;            }        </style>    </head>        <body>        <div class="pad">            <h2>パスワードがリセットされました。</h2>            <p>            Tour Password has been set. You may so ahead and login            </p>            <br>            <a href="{% url 'photo:index' %}">Photo Galleryのトップページ</a>        </div>    </body></hmtl>          

accounts/templates/password_reset_form.html
<! doctype html><html lang="ja">    <head>        <style>            .pad{            background-color: lavender;            border: solid 2px;            padding-top: 30px;            padding-bottom: 50px;            padding-left: 100px;            margin-top: 50px;            maegin-right: 70px;            margin-left: 70px;            }        </style>    </head>        <body>        <div class="pad">            <h2>Photo Gallery</h2>            <h4>            新しいパスワードを２回入力してください。これにより、            正しく入力したことが確認されます。            </h4>            <br />                        <form action="" method="POST">                {% csrf_token %}                {{form}}                <input type="submit" value="パスワードリセット"/>            </form>        </div>    </body></hmtl>            

accounts/templates/password_reset_sent.html
{% extends 'base.html' %}{% block title %}Send Password reset{% endblock %}    {% block contents %}    <hr>    <div class="conainer">        <div class="row">            <div class="col offset-2 py-4">                <h5>パスワードのリセット手順をメールで送信しました。                    メールはすぐに届きます。</h5>                <br>                <h6>メールが届かない場合は、登録済みのメールアドレスであるかを確認し、迷惑フォルダーも確認してみてください</h6>                <br>                <a href="{% url 'photo:index' %}">Photo Gallery</a>            </div>        </div>    </div>    {% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}{% block title %}Sign up{% endblock %}    {% block contents %}        <hr>    <div class = "container">         <div class = "row">         <div class = "col offet-2">             <h3>サインアップ</h3>             <form method = "post">                {% csrf_token %}                {% for field in form %}                <p>                  {{ field.label_tag }}<br>                  {{ field }}                  {% if field.help_text %}                      <small style="collor: gray">{{ field.help_text }}</small>                  {% endif %}                  {% for error in field.errors %}                      <p style="collor: red">{{ error }}</p>                  {% endfor %}              </p>              {% endfor %}              <p style="collor:red">                  ※メールアドレスはパスワードをリセットする際に必要になりますので、登録をお願いします。              </p>              <input type="submit" value="Sign up">            </form>            <br>            <p><a href="{% url 'photo:index' %}">                登録をやめてトップページに戻る</a>            </p>         </div>         </div>    </div>    {% endblock %}                    

accounts/templates/signup_success.html
{% extends 'base.html' %}{% block title %}Registration Complete{% endblock %}{% block contents %}<div class="container">    <div class="row">        <div class="col offset-4 py-4">            <h3>登録が完了しました</h3>            <p><a href="{% url 'accounts:login' %}">ログインはこちら</a></p>        </div>    </div></div>{% endblock %}

photo/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更-->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <!-- ヘッダー情報のタイトルを個別に設定できるようにする-->
    <title>{% block title %}{% endblock %}</title>
    
    <link rel="icon" type="image/x-icon"
          href={% static 'assets/favicon.ico' %} />

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSSを読み込むコードをBootstrapからコピー-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>    
  </head>
  
  <body>
    <!-- ページのヘッダー-->
    <header>
      <!-- ナビゲーションバーのヘッダー-->
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <!-- ヘッダーのタイトルと本文-->
              <h4 class="text-white">お気に入りを見つけよう！</h4>
              <p class="text-muted">
                誰でも参加できる写真投稿サイトです。
                自分で撮影した写真なら何でもオッケー！
                でも、カテゴリに属する写真に限ります。
                コメントも付けてください！
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <!-- ナビゲーションメニュー-->
                {% if user.is_authenticated %}
                <!-- ログイン中のメニュー-->
                <li><a href="{% url 'photo:mypage' %}"
                       class="text-white">マイページ</a></li>
                
                <li><form method="POST" action="{% url 'accounts:logout' %}" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="text-white" style="background: none; border: none; cursor: pointer;">ログアウト</button>
                </form></li>
                       
                <li><a href="{% url 'password_reset' %}"
                       class="text-white">パスワードのリセット</a></li>
                <li><a href="mailto:admin@example.com"
                       class="text-white">Email me</a></li>
                {% else %}
                <!-- ログイン状態ではない場合のメニュー-->
                <li><a href="{% url 'accounts:signup' %}"
                       class="text-white">サインアップ</a></li>
                <li><a href="{% url 'accounts:login' %}"
                       class="text-white">ログイン</a></li>
                <li><a href="mailto:admin@example.com"
                       class="text-white">Email me</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- ナビゲーションバー-->
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <!-- トップページへのリンク-->
          <a href="{% url 'photo:index' %}"
             class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="20" height="20" fill="none"
                 stroke="currentColor"
                 stroke-linecap="round"
                 stroke-linejoin="round"
                 stroke-width="2"
                 aria-hidden="true"
                 class="me-2"
                 viewBox="0 0 24 24">
                 <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                 <circle cx="12" cy="13" r="4"/></svg>
            <!-- リンクテキスト-->
            <strong>Photo Gallery</strong>
          </a>
          <!-- トグルボタン-->
          <button class="navbar-toggler"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarHeader"
                  aria-controls="navbarHeader"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>
    
    <!-- メインコンテンツ-->
    <main>
      <!-- <main>タグの要素をすべて削除して以下に書き換え-->
      <!-- メインコンテンツの本体部分は各ページのテンプレートで埋め込む-->
      {% block contents %}{% endblock %}
    </main>
    
    <!-- フッター -->
    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="#">Back to top</a>
        </p>
        <!-- フッターのテキストを任意のものに書き換え-->
        <p class="mb-1">
          Photo Gallery is &copy; Bootstrap, but please post a lot!</p>
      </div>
    </footer>
    
    <!-- BootstrapからJavaScriptを読み込むコードをコピーして貼り付け-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>      
  </body>
</html>

photo/templates/detail.html
{% extends 'base.html' %}{% block title %}Photo Detail{% endblock %}    {% block contents %}    <br>    <div class="container">        <div class="row">            <div class="col offset-3">                <h2>{{object.title}}</h2>                <p>{{object.comment}}</p>                <br>                                <p>{{object.posted_at}}に投稿</p>                <p><img src="{{ object.image1.url }}"></img></p>                                {% if object.image2 %}                <p><img src="{{ object.image2.url }}"></img></p>                {% endif %}                                {% if request.user == object.user %}                <a href="{% url 'photo:photo_delete' object.pk %}"                class="btn btn-primary my-2">削除する</a>                {% endif %}                            </div>        </div>    </div>    {% endblock %}                

photo/templates/index.html
{% extends 'base.html' %}{% block title %}Photo Gallery{%endblock %}    {% block contents %}    {% include "photos_title.html" %}    {% include "photos_list.html" %}    {% include "pagination.html" %}        {% endblock %}

photo/templates/mypage.html
{% extends 'base.html' %}{% block title %}Mypage{% endblock %}    {% block contents %}        {% if user.is_authenticated %}    <br>    <div style="text-align:center">    <h4>{{user.username}}さんのマイページ</h4>        {% if object_list.count == 0 %}            <p>{{user.username}}さんの投稿はありません</p>        {% else %}            <p>投稿<strong>{{object_list.count}}件</p>        {% endif %}        <a href="{% url 'photo:post' %}">投稿する</a>        </div>        <hr>    {% endif %}        {% include "photos_list.html" %}    {% include "pagination.html" %}        {% endblock %}

photo/templates/pagination.html
<!-- ページネーションのアイコンを左右中央に配置 --><ul class="pagination"    style="justify-content:center">    <!--    前ページを表示するアイコンとリンクの設定    ページネーションされたPageオブジェクトをorderby_recordsで取得    Page.has_previous: 直前にページがある場合にTrueを返す    -->    {% if page_obj.has_previous %}    <!--    前のページが存在する場合はそのページへのリンクが設定されたアイコン[<<]を表示    Page.previous_page_number: 直前のページ番号を返す    -->    <li class="page-item">        <a class="page-link"        　　 href="?page={{ page_obj.previous_page_number }}"        　　 aria-label="Previous">          <span aria-hidden="true">&laquo;</span>        </a>    </li>    {% endif %}    <!--     すべてのページについてページ番号のアイコンを表示     paginator.page_range: [1, 2, 3, 4] のように1から始まるページ番号を返す     page_obj.paginator.page_rangeとして取得     ブロックパラメーターnumに順次取り出される    -->    {% for num in page_obj.paginator.page_range %}        <!--        各ページのアイコンを出力        Page.number: 引き渡されたページのページ番号を返す        -->        {% if page_obj.number == num %}        <!--        処理中のページ番号が引き渡されたページのページ番号と一致する場合は        ページ番号のアイコン(アクティブ状態)を表示(リンクは設定しない)        -->        <li class="page-item active">            <span class="page-link">{{ num }}</span>        </li>        <!--        ページ番号が引き渡されたページのページ番号と一致しない場合        -->        {% else %}        <!--        ページ番号のアイコン(アクティブ状態ではない)にリンクを設定して表示        -->        <li class="page-item">            <a class="page-link" href="?page={{ num }}">{{ num }}</a>        </li>        {% endif %}    {% endfor %}    <!--    次ページへのリンクを示すアイコンの表示    Page.has_next: 次のページがある場合にTrueを返す    -->    {% if page_obj.has_next %}    <!--    次ページが存在する場合はリンクを設定したアイコン［>>]を表示    Page.next_page_number: 次のページ番号を返す    -->    <li class="page-item">        <a class="page-link"           href="?page={{ page_obj.next_page_number }}"           aria-label="Next">            <span aria-hidden="true">&raquo;</span>        </a>    </li>    {% endif %}</ul>

photo/templates/photo_delete.html
{% extends 'base.html' %}{% block title %}Photo Delete{% endblock %}    {% block contents %}    <br>    <div class="container">        <div class="row">            <div class="col offset-3">                <form method="POST">                <br>                <p>削除してもいいですか？</p>                {% csrf_token %}                <button class="btn btn-primary my-2"                    type="submit">削除</button>                <a href="{% url 'photo:photo_detail' object.pk %}"                    class="btn btn-secondary my-2">キャンセル</a>                            </div>        </div>    </div>    {% endblock %}

photo/templates/photos_list.html
  <div class="album py-5 bg-light">
    <!-- Bootstrapのグリッドシステムを適用 -->
    <div class="container">
      <!-- 行要素を配置 -->
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <!-- 列要素を配置 -->
        {% for record in object_list %}
        <div class="col">
          <div class="card shadow-sm">
              <img src="{{ record.image1.url }}"
                   class="bd-placeholder-img card-img-top"
                   width="100%" height="225"
                   role="img">

            <!-- タイトルとボタンを出力するブロック -->
            <div class="card-body">
              <p class="card-text">
              {{ record.title }}
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button"
                          class="btn btn-sm btn-outline-secondary"
                          onclick="location.href='{% url 'photo:photo_detail' record.pk %}'">
                          View</button>
                  <!-- テキストを変更 -->
                  <button type="button"
                          class="btn btn-sm btn-outline-secondary"
                          onclick="location.href='{% url 'photo:photos_cat' category=record.category.id %}'">
                          {{ record.category.title }}</button>
                </div>
                <!-- <small>タグのテキストを変更-->
                <a href="{% url 'photo:user_list' user=record.user.id %}">
                <small class="text-muted">
                {{ record.user.username }}</small></a>
              </div>
            </div>
          </div>
        <!-- 列要素ここまで -->
        </div>
      <!-- 行要素ここまで -->
      {% endfor %}
      </div>
    <!-- グリッドシステムここまで -->
    </div>
  </div>

photo/templates/photos_title.html
  <!-- タイトルとナビゲーションボタン -->
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <!-- タイトルと本文 -->
        <h1 class="fw-light">Photo Gallery</h1>
        <p class="lead text-muted">
          コメントを見て写真に描かれた世界に思いを馳せましょう。
          素敵な写真とコメントをお待ちしています!</p>
        <p>
          <!-- ナビゲーションボタン -->
        <div class="d-flex justify-content-center">
            {% if user.is_authenticated %}
                <a href="{% url 'photo:post' %}" class="btn btn-primary my-2 mx-2">投稿する</a>
        
                <form method="POST" action="{% url 'accounts:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-secondary my-2">ログアウト</button>
                </form>
            {% else %}
                <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2 mx-2">今すぐサインアップ</a>
                <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">登録済みの方はログイン</a>
            {% endif %}
        </div>
        </p>
      </div>
    </div>
  </section>

photo/templates/post_photo.html
{% extends 'base.html' %}{% block title %}Post{% endblock %}    {% block contents %}    <br>    <div class="container">        <div class="row">            <div class="col offset-2">                <form method="POST" enctype="multipart/form-data">                {% csrf_token %}                    <table>                        <tr>                            <th>カテゴリ</th>                            <td>{{ form.category }}</td>                        </tr>                        <tr>                            <th>タイトル</th>                            <td>{{ form.title }}</td>                        </tr>                        <tr>                            <th>コメント</th>                            <td>{{ form.comment }}</td>                        </tr>                        <tr>                            <th>画像1</th>                            <td>{{ form.image1 }}</td>                        </tr>                        <tr>                            <th>画像2</th>                            <td>{{ form.image2 }}</td>                        </tr>                    </table>                    <hr>                    <button type="submit">投稿する</button>                </form>            </div>        </div>    </div>    {% endblock %}

photo/templates/post_success.html
{% extends 'base.html' %}{% block title %}Post Success{% endblock %}    {% block contents %}        <br><br>    <div class="container">        <div class="row">            <div class="col offset-2">                <h4>投稿が完了しました！</h4>            </div>        </div>    </div>    {% endblock %}